### ISSUE TITLE
Arrive action not required to be used as the first action of a turn by underlings

### ISSUE THREAD

**Issue by JonEstes** [camyosh/tablestuck#15]
Arrive should only be usable as the first action of a turn, however underlings are able to use it at other times during their turns.
![image](https://user-images.githubusercontent.com/60444382/113522078-d73bec80-956b-11eb-817f-8f62f62108b2.png)

**Comment by DocZane** [comment]
Underlings will now always and only use arrive first, if they have it at their disposal.
